stages:
  data_ingestion:
    cmd: python src/CNN_Classifier/pipeline/stage1_data_ingestion.py
    deps:
      - src/CNN_Classifier/pipeline/stage1_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/kidney-ct-scan-image


  prepare_base_model:
    cmd: python src/CNN_Classifier/pipeline/stage2_base_model.py
    deps:
      - src/CNN_Classifier/pipeline/stage2_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/CNN_Classifier/pipeline/stage3_train_model.py
    deps:
      - src/CNN_Classifier/pipeline/stage3_train_model.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5


  evaluation:
    cmd: python src/CNN_Classifier/pipeline/stage4_evaluate_withmlflow.py
    deps:
      - src/CNN_Classifier/pipeline/stage4_evaluate_withmlflow.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false